package org.geysermc.hydraulic.compat.adapter;

public enum AdapterFeature {
    BLOCK_ITEM_TEXTURE_FALLBACK,
    BLOCK_CREATIVE_EXPOSURE,
    BLOCK_PLACEMENT,
    MENU_FALLBACK_TRANSLATION,
    BLOCK_ENTITY_PATCH_TRANSLATION,
    CUSTOM_ITEM_REGISTRATION,
    ITEM_CREATIVE_EXPOSURE,
    WEARABLE_ITEM_PRESENTATION,
    ATTACHABLE_ITEM_PRESENTATION,
    CUSTOM_ENTITY_REGISTRATION,
    ENTITY_INTERACTION_PROMPT,
    FLUID_BUCKET_TEXTURE_FALLBACK
}
