package org.geysermc.hydraulic.compat.adapter;

public enum AdapterFeature {
    BLOCK_ITEM_TEXTURE_FALLBACK,
    BLOCK_CREATIVE_EXPOSURE,
    BLOCK_PLACEMENT,
    CUSTOM_ITEM_REGISTRATION,
    ITEM_CREATIVE_EXPOSURE,
    WEARABLE_ITEM_PRESENTATION,
    ATTACHABLE_ITEM_PRESENTATION,
    CUSTOM_ENTITY_REGISTRATION
}